const KEY='trackme-v1';
const defaultState={theme:'light',habits:[{id:'dsa',name:'DSA',icon:'🧠'},{id:'project',name:'Career / Project',icon:'💻'},{id:'exercise',name:'Exercise',icon:'🏋️'},{id:'sleep',name:'Sleep 7+ hrs',icon:'😴'},{id:'scroll',name:'Low scrolling',icon:'📵'}],days:{},goals:[]};
let state=load();
let selectedDate=todayStr();

function load(){try{return {...structuredClone(defaultState),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));flashSaved()}
function dayKey(d=selectedDate){return d}
function getDay(date=selectedDate){if(!state.days[date])state.days[date]={priorities:['','',''],priorityDone:[false,false,false],habits:{},time:{dsa:0,project:0,exercise:0,scroll:0},reflection:{best:'',waste:'',improve:''}};return state.days[date]}
function todayStr(){const d=new Date();return d.toLocaleDateString('en-CA')}
function clamp(n,min,max){return Math.min(max,Math.max(min,n))}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function init(){document.getElementById('datePicker').value=selectedDate;applyTheme();bindNav();bindStatic();renderAll();setGreeting()}
function setGreeting(){const h=new Date().getHours();document.getElementById('greeting').textContent=h<12?'GOOD MORNING':h<17?'GOOD AFTERNOON':'GOOD EVENING'}
function bindNav(){document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(b.dataset.page+'Page').classList.add('active');document.getElementById('pageTitle').textContent={dashboard:'Your day, at a glance.',analytics:'See the pattern, not just the day.',goals:'Keep the long game visible.',settings:'Make TrackMe yours.'}[b.dataset.page];if(b.dataset.page==='analytics')renderAnalytics();if(b.dataset.page==='goals')renderGoals();if(b.dataset.page==='settings')renderSettings();document.getElementById('sidebar').classList.remove('open')})}
function bindStatic(){
 document.getElementById('datePicker').onchange=e=>{selectedDate=e.target.value;renderDashboard()};
 document.getElementById('themeToggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';applyTheme();save()};
 document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
 ['timeDsa','timeProject','timeExercise','timeScroll'].forEach(id=>document.getElementById(id).oninput=e=>{const k=id.replace('time','').toLowerCase();getDay().time[k]=Math.max(0,Number(e.target.value)||0);save();renderProgressOnly()});
 [['reflectionBest','best'],['reflectionWaste','waste'],['reflectionImprove','improve']].forEach(([id,k])=>document.getElementById(id).oninput=e=>{getDay().reflection[k]=e.target.value;save()});
 document.getElementById('quickAddHabit').onclick=()=>{document.querySelector('[data-page=settings]').click();document.getElementById('newHabitName').focus()};
 document.getElementById('addHabitBtn').onclick=addHabit;document.getElementById('newHabitName').addEventListener('keydown',e=>{if(e.key==='Enter')addHabit()});
 document.getElementById('addGoalBtn').onclick=()=>document.getElementById('goalDialog').showModal();
 document.getElementById('goalForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const name=document.getElementById('goalName').value.trim();const target=Number(document.getElementById('goalTarget').value)||1;if(!name)return;state.goals.push({id:crypto.randomUUID(),name,current:Number(document.getElementById('goalCurrent').value)||0,target,unit:document.getElementById('goalUnit').value.trim()||'units'});save();e.target.reset();document.getElementById('goalCurrent').value=0;document.getElementById('goalTarget').value=100;renderGoals()});
 document.getElementById('exportBtn').onclick=exportData;document.getElementById('importFile').onchange=importData;document.getElementById('resetBtn').onclick=()=>{if(confirm('Delete all TrackMe data from this browser?')){state=structuredClone(defaultState);save();renderAll()}};
}
function applyTheme(){document.body.classList.toggle('dark',state.theme==='dark')}
function renderAll(){renderDashboard();renderAnalytics();renderGoals();renderSettings()}
function renderDashboard(){const d=getDay();renderPriorities(d);renderHabits(d);document.getElementById('timeDsa').value=d.time.dsa||'';document.getElementById('timeProject').value=d.time.project||'';document.getElementById('timeExercise').value=d.time.exercise||'';document.getElementById('timeScroll').value=d.time.scroll||'';document.getElementById('reflectionBest').value=d.reflection.best||'';document.getElementById('reflectionWaste').value=d.reflection.waste||'';document.getElementById('reflectionImprove').value=d.reflection.improve||'';renderProgressOnly()}
function renderPriorities(d){const list=document.getElementById('prioritiesList');list.innerHTML='';for(let i=0;i<3;i++){const row=document.createElement('div');row.className='priority-row'+(d.priorityDone[i]?' done':'');row.innerHTML=`<input class="check" type="checkbox" ${d.priorityDone[i]?'checked':''}><input type="text" maxlength="80" placeholder="Priority ${i+1}" value="${esc(d.priorities[i]||'')}"><button class="priority-delete" title="Clear">×</button>`;const [check,text,del]=row.children;check.onchange=()=>{d.priorityDone[i]=check.checked;save();renderDashboard()};text.oninput=()=>{d.priorities[i]=text.value;save();renderProgressOnly()};del.onclick=()=>{d.priorities[i]='';d.priorityDone[i]=false;save();renderDashboard()};list.appendChild(row)}}
function renderHabits(d){const list=document.getElementById('habitsList');list.innerHTML='';state.habits.forEach(h=>{const on=!!d.habits[h.id];const item=document.createElement('div');item.className='habit-item';item.innerHTML=`<label><span class="habit-icon">${h.icon||'✓'}</span><span>${esc(h.name)}</span></label><input class="check" type="checkbox" ${on?'checked':''}>`;item.querySelector('input').onchange=e=>{d.habits[h.id]=e.target.checked;save();renderProgressOnly()};list.appendChild(item)})}
function completionForDate(date){const d=state.days[date];if(!d)return 0;const filled=d.priorities.filter(x=>x.trim()).length;const prDone=d.priorityDone.filter((x,i)=>x&&d.priorities[i]?.trim()).length;const habitDone=state.habits.filter(h=>d.habits?.[h.id]).length;const denom=filled+state.habits.length;if(!denom)return 0;return Math.round(((prDone+habitDone)/denom)*100)}
function renderProgressOnly(){const d=getDay();const pct=completionForDate(selectedDate);document.getElementById('progressText').textContent=pct+'%';document.getElementById('progressFill').style.width=pct+'%';document.getElementById('scoreRingText').textContent=pct;document.getElementById('scoreRing').style.background=`conic-gradient(var(--accent) ${pct*3.6}deg,var(--surface2) 0deg)`;const prDone=d.priorityDone.filter((x,i)=>x&&d.priorities[i]?.trim()).length;document.getElementById('priorityCounter').textContent=`${prDone}/3`;const mins=(d.time.dsa||0)+(d.time.project||0)+(d.time.exercise||0);document.getElementById('focusTime').textContent=formatMins(mins);document.getElementById('productiveHours').textContent=formatMins(mins);document.getElementById('progressMessage').textContent=pct>=80?'Strong day. Finish clean and protect the streak.':pct>=50?'Good momentum — one more focused block can move the day.':'Start small: finish one priority and one habit.';const streak=calcStreak();document.getElementById('streakCount').textContent=streak;document.getElementById('sideStreak').textContent=streak+' days'}
function formatMins(m){if(m<60)return `${m}m`;const h=Math.floor(m/60),r=m%60;return r?`${h}h ${r}m`:`${h}h`}
function calcStreak(){let streak=0;let d=new Date();for(let i=0;i<365;i++){const k=d.toLocaleDateString('en-CA');if(completionForDate(k)>0){streak++}else if(k!==todayStr()){break}else if(k===todayStr()&&completionForDate(k)===0){}d.setDate(d.getDate()-1)}return streak}
function weekDates(){const arr=[];const d=new Date();for(let i=6;i>=0;i--){const x=new Date(d);x.setDate(d.getDate()-i);arr.push(x)}return arr}
function renderAnalytics(){const dates=weekDates();const pcts=dates.map(d=>completionForDate(d.toLocaleDateString('en-CA')));const avg=Math.round(pcts.reduce((a,b)=>a+b,0)/7);document.getElementById('weekConsistency').textContent=avg+'%';let pr=0,mins=0;dates.forEach(x=>{const d=state.days[x.toLocaleDateString('en-CA')];if(!d)return;pr+=d.priorityDone.filter((v,i)=>v&&d.priorities[i]?.trim()).length;mins+=(d.time.dsa||0)+(d.time.project||0)+(d.time.exercise||0)});document.getElementById('weekPriorities').textContent=pr;document.getElementById('weekFocus').textContent=formatMins(mins);const chart=document.getElementById('weeklyChart');chart.innerHTML='';dates.forEach((x,i)=>{const c=document.createElement('div');c.className='bar-col';c.innerHTML=`<div class="bar-wrap"><div class="bar" style="height:${pcts[i]}%" title="${pcts[i]}%"></div></div><span>${x.toLocaleDateString('en-US',{weekday:'short'})}</span>`;chart.appendChild(c)});const hA=document.getElementById('habitAnalytics');hA.innerHTML='';state.habits.forEach(h=>{let n=0;dates.forEach(x=>{if(state.days[x.toLocaleDateString('en-CA')]?.habits?.[h.id])n++});const pct=Math.round(n/7*100);hA.insertAdjacentHTML('beforeend',`<div class="analytics-row"><span>${esc(h.name)}</span><div class="mini-track"><div style="width:${pct}%"></div></div><b>${n}/7</b></div>`)});const best=Math.max(...pcts),bi=pcts.indexOf(best);document.getElementById('insightText').textContent=best>0?`${dates[bi].toLocaleDateString('en-US',{weekday:'long'})} is your strongest day this week at ${best}% completion. Your 7-day average is ${avg}%. ${avg<50?'Focus on making the minimum version of each habit easier to complete.':'Keep the system stable before adding more habits.'}`:'Log your priorities and habits for a few days. Your strongest days and consistency patterns will appear here.'}
function addHabit(){const input=document.getElementById('newHabitName');const name=input.value.trim();if(!name)return;state.habits.push({id:'h_'+Date.now(),name,icon:'✓'});input.value='';save();renderSettings();renderDashboard();renderAnalytics()}
function renderSettings(){const box=document.getElementById('settingsHabits');box.innerHTML='';state.habits.forEach(h=>{const div=document.createElement('div');div.className='settings-habit';div.innerHTML=`<span>${h.icon||'✓'} ${esc(h.name)}</span><button>Remove</button>`;div.querySelector('button').onclick=()=>{if(confirm(`Remove "${h.name}"? Existing history will remain in your backup data.`)){state.habits=state.habits.filter(x=>x.id!==h.id);save();renderAll()}};box.appendChild(div)})}
function renderGoals(){const list=document.getElementById('goalsList');list.innerHTML='';if(!state.goals.length){list.innerHTML='<article class="card"><h3>No goals yet</h3><p class="muted">Create a measurable goal such as “Solve 200 DSA problems” or “Exercise 100 days”.</p></article>';return}state.goals.forEach(g=>{const pct=clamp(Math.round((g.current/g.target)*100),0,100);const card=document.createElement('article');card.className='card goal-card';card.innerHTML=`<p class="eyebrow">${pct}% COMPLETE</p><h3>${esc(g.name)}</h3><div class="goal-numbers"><span>${g.current} ${esc(g.unit)}</span><span>${g.target} ${esc(g.unit)}</span></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><div class="goal-actions"><input type="number" min="0" value="${g.current}"><button class="primary-button">Update</button><button class="danger-button">Delete</button></div>`;const [input,update,del]=card.querySelector('.goal-actions').children;update.onclick=()=>{g.current=Math.max(0,Number(input.value)||0);save();renderGoals()};del.onclick=()=>{state.goals=state.goals.filter(x=>x.id!==g.id);save();renderGoals()};list.appendChild(card)})}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='trackme-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();applyTheme();renderAll();alert('Backup imported successfully.')}catch{alert('That file is not a valid TrackMe backup.')}};r.readAsText(f)}
let saveTimer;function flashSaved(){const el=document.getElementById('saveIndicator');if(!el)return;el.textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>el.textContent='Saved',350)}
init();
